server:
  port: ${PORT:8080}
spring:
  application:
    name: DevTales
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  boot:
    admin:
      client:
        url: ${ADMIN_SERVER_URL}
        username: ${ADMIN_NAME}
        password: ${ADMIN_PASSWORD}
  jpa:
    hibernate.ddl-auto: none
    show-sql: false
  flyway:
    enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: 465
    protocol: smtps
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  security.enabled: false

mail:
  debug: true
cloudinary:
  cloud-name: ${CLOUD_NAME}
  api-key: ${API_KEY}
  api-secret: ${API_SECRET}

blog:
  title: DevTales
  subtitle: Сказочки разработчиков
  phone: +7 (987) 654-32-10
  email: alexandr.maruchek@gmail.com
  copyright: Alexandr Maruchek
  copyrightFrom: 2021