spring.jpa.hibernate.ddl-auto: create-drop
spring.datasource.url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/devtales
spring.datasource.username: root
spring.datasource.password: Zabbil@3qew8Nbi1984
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true

blog.title: DevPub
blog.subtitle: Рассказы разработчиков
blog.phone: +7 903 666-44-55
blog.email: mail@mail.ru
blog.copyright: Дмитрий Сергеев
blog.copyrightFrom: 2005