spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
captcha:
  width-origin: 150
  width-new: 100
  height-origin: 50
  height-new: 35
  image: data:captchaImage/png;base64,
  lifespanBySec: 0
avatar:
  basic_url: https://robohash.org/
  avatar_config: .png?size=360x360&set=set


blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 987 654-32-10
  email: alexandr.maruchek@gmail.com
  copyright: Александр Маручек
  copyrightFrom: 1984