spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/devtales?createDatabaseIfNotExist=true
         &allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true
         &characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Zabbil@3qew8Nbi1984
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true


blog.title: DevPub
blog.subtitle: Рассказы разработчиков
blog.phone: +7 987 654-32-10
blog.email: alexandr.maruchek@gmail.com
blog.copyright: Александр Маручек
blog.copyrightFrom: 1984