INSERT INTO users (code, email, is_moderator, name, password, photo, reg_time)
VALUES ('LSACSNO', 'mailone@example.ru', 0, 'Egor Petrov',
        '$2a$12$7kSleRW1Lnv24ygiuZ5yB.3IUczHQbt1wBxpz02HJbLBDDoIySAKi',
        'https://robohash.org/mailme@example.ru.png?size=350x350&set=set1',
        '2021-12-23 15:32:01'),
       ('Bxpz02HJbL', 'mailtwo@example.ru', 0, 'Сергей Хмуров',
        '$2a$12$nvklXKkTOE.MLupPLIScbeQ.OIJI4X3Rvszdhoii3Ogvsi9O6r3me',
        'https://robohash.org/nesergeychmurov?size=350x350&set=set2',
        '2021-12-24 12:20:01'),
       ('OIJI4X3Rv', 'mailthree@example.ru', 1, 'Алексей Прохоров',
        '$2a$12$Ic9HK.72/LSACSNOo3.0k.0Cne0h.mzaSm0ziiZEPotQm.CfHEkNm',
        'https://robohash.org/nesergeychmurov?size=350x350&set=set2',
        '2021-12-27 11:52:15'),
       ('ziiZEP', 'mailfour@example.ru', 0, 'Максим Титов',
        '$2a$12$xTDmyM6xcrMI3GoatFjOxulPLZwuz.zP4XVbij7EqFiOXG0Xb..46',
        'https://robohash.org/necessimvero?size=350x350&set=set1',
        '2022-01-13 15:01:09'),
       ('pz02HJb', 'mailfive@example.ru', 1, 'Владимир Тутов',
        '$2a$12$7kSleRW1Lnv24ygiuZ5yB.3IUczHQbt1wBxpz02HJbLBDDoIySAKi',
        'https://robohash.org/mailfive@example.ru.png?size=350x350&set=set3',
        '2022-01-13 19:30:11'),
       ('ziiZEPot', 'JamesGosling@example.ru', 1, 'James Gosling',
        '$2a$12$Ic9HK.72/LSACSNOo3.0k.0Cne0h.mzaSm0ziiZEPotQm.CfHEkNm',
        'https://robohash.org/necessimvero?size=350x350&set=set2',
        '2022-01-15 16:44:01'),
       ('QdYLCFL6', 'mailsix@example.ru', 0, 'Евгений Толкунов',
        '$2a$12$3znWAMhz4ZV5Gj9jMfG7XeGzo.VEfJDT4QdYLCFL6CB03zBlSbZqS',
        'https://robohash.org/mailfive@example.ru.png?size=350x350&set=set1',
        '2022-01-23 22:40:10');

INSERT INTO posts (date_time, is_active, moderation_status, text, title, view_count, moderator_id, user_id)
VALUES ('2021-12-31 15:12:01', 1, 'ACCEPTED',
        'What are the pros and cons of a particular programming language? Is X a good language for my task? Googling “best programming language” will give you a standard list of “Python, Java, JavaScript, C#, C++, PHP” with a vague list of pros and cons.',
        'These Modern Programming Languages Will Make You Suffer', 0, 3, 1),
       ('2021-12-21 23:42:45', 1, 'ACCEPTED',
        'Java may still be getting bad press when it comes to (mostly consumer) security, but it continues to be the world`s most popular software development language.',
        'Java: Still the Most Popular Programming Language', 0, 5, 2),
       ('2022-01-17 00:02:00', 1, 'ACCEPTED',
        '"Генерация случайных чисел слишком важна, чтобы оставлять ее на волю случая" - Роберт Р. Кавью. Как-то поздним летним вечером мне пришлось разобраться, как устроены генераторы случайных чисел в Windows и Linux.',
        'Генераторы случайных чисел в разных ОС', 12, 3, 2),
       ('2022-01-13 14:37:01', 1, 'ACCEPTED',
        'Каждый веб-разработчик знает, что такое текст-«рыба». Текст этот, несмотря на название, не имеет никакого отношения к обитателям водоемов. Используется он веб-дизайнерами для вставки на интернет-страницы и демонстрации внешнего вида контента, просмотра шрифтов, абзацев, отступов и т.д. Так как цель применения такого текста исключительно демонстрационная, то и смысловую нагрузку ему нести совсем необязательно. Более того, нечитабельность текста сыграет на руку при оценке качества восприятия макета. Самым известным «рыбным» текстом является знаменитый Lorem ipsum. Считается, что впервые его применили в книгопечатании еще в XVI веке. Своим появлением Lorem ipsum обязан древнеримскому философу Цицерону, ведь именно из его трактата «О пределах добра и зла» средневековый книгопечатник вырвал отдельные фразы и слова, получив текст-«рыбу», широко используемый и по сей день. Конечно, возникают некоторые вопросы, связанные с использованием Lorem ipsum на сайтах и проектах, ориентированных на кириллический контент – написание символов на латыни и на кириллице значительно различается. И даже с языками, использующими латинский алфавит, могут возникнуть небольшие проблемы: в различных языках те или иные буквы встречаются с разной частотой, имеется разница в длине наиболее распространенных слов. Отсюда напрашивается вывод, что все же лучше использовать в качестве «рыбы» текст на том языке, который планируется использовать при запуске проекта. Сегодня существует несколько вариантов Lorem ipsum, кроме того, есть специальные генераторы, создающие собственные варианты текста на основе оригинального трактата, благодаря чему появляется возможность получить более длинный неповторяющийся набор слов.',
        'Что такое текст-«рыба»', 0, 3, 2),
       (current_time() - interval 1 day, 1, 'ACCEPTED',
        '1. Обзор Довольно типично иметь get и set методы в наших предметных объектах, но есть и другие способы, которые мы можем найти более выразительными. В этом уроке мы узнаем о Project Lombok ‘s @Accessories аннотации и его поддержке свободных, цепных и пользовательских методов доступа. Однако, прежде чем продолжить, нашей IDE потребуется установить Lombok. 2. Стандартные аксессуары Прежде чем мы рассмотрим аннотации @Accessors , давайте рассмотрим, как Ломбок обрабатывает аннотации @Getter и @Setter по умолчанию.',
        'Использование аннотации @Accessors Ломбока', 3, 5, 6),
       (current_time() - interval 2 day, 1, 'ACCEPTED',
        'Let’s first consider the reasons why you may need to do a redirect in a Spring application. There are many possible examples and reasons of course. One simple one might be POSTing form data, working around the double submission problem, or just delegating the execution flow to another controller method. A quick side note here is that the typical Post/Redirect/Get pattern doesn''t adequately address double submission issues – problems such as refreshing the page before the initial submission has completed may still result in a double submission.',
        'A Guide To Spring Redirects', 5, 3, 2),
       (current_time() - interval 3 day, 0, 'NEW',
        'Команда git stash предназначена для того, чтобы поместить текущие изменения, которые вы выполнили в файлах, в отдельное хранилище, и вернуть файлы к исходному состоянию. То есть git stash прячет изменения в файлах и сохраняет эти изменения отдельно, чтобы потом можно было их вернуть. Для чего нужен git stash. Приведем пример. Например, вы выполнили какие-нибудь изменения в файлах и хотите переключиться на другую ветку, но чтобы там не было ваших текущих изменений. С помощью команды git stash можно спрятать эти изменения. Ваши изменения помещаются в отдельное хранилище — в стек, а вы можете спокойно переключиться на другую ветку. Всё, что вы прячете с помощью git stash, попадает в отдельный список. Затем вы можете извлекать оттуда то, что вы туда спрятали — ваши «прятанья» (далее по тексту будет использоваться это слово).',
        'Команда Git stash. Как прятать изменения в Git', 0, NULL, 1),
       (current_time() - interval 4 day, 1, 'ACCEPTED',
        '<span style="color: rgb(51, 51, 51); font-family: &quot;YS Text&quot;, Arial, Helvetica, sans-serif; font-size: 13px; background-color: rgb(251, 251, 251);">Психологический термин, означающий изменение в восприятии времени, при котором время может ощущаться растянутым или сжатым, невзирая на фактическую длину временного отрезка. При замедлении времени могут создаваться оптические иллюзии размытия движущегося объекта. Дисторсия времени может также вызывать искаженное восприятие прошлого или будущего. Порой протекает бессознательно. Причиной изменения восприятия часто являются психологические травмы, физическая активность, прием веществ, влияющих на психическое состояние и сознание.</span><div><span style="color: rgb(51, 51, 51); font-family: &quot;YS Text&quot;, Arial, Helvetica, sans-serif; font-size: 13px; background-color: rgb(251, 251, 251);"><br></span></div><div><span style="color: rgb(51, 51, 51); font-family: &quot;YS Text&quot;, Arial, Helvetica, sans-serif; font-size: 13px; background-color: rgb(251, 251, 251);"><img src="http://res.cloudinary.com/devtales/image/upload/v1642797759/upload/jfQS/O5tM/1WD7/mailthree%40example.ru.jpg"><br></span></div>',
        'Быстротечность времени...', 1, 3, 6),
       (current_time() - interval 5 day, 1, 'ACCEPTED',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, ut labore et dolore magna aliqua sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Feugiat pretium nibh ipsum consequat nisl vel pretium lectus.',
        'Generated Lorem Ipsum placeholder text', 3, 5, 6),
       (current_time() - interval 6 day, 1, 'ACCEPTED',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Feugiat pretium nibh ipsum consequat nisl vel pretium lectus.',
        'Generated Lorem Ipsum placeholder text', 5, 3, 2),
       (current_time() - interval 7 day, 0, 'DECLINED',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        'Fifth post. Generated Lorem Ipsum placeholder text', 0, NULL, 1),
       (current_time() - interval 8 day, 1, 'ACCEPTED',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        'Sixth post. Generated Lorem Ipsum placeholder text', 1, 3, 6),
       (current_time() - interval 2 day, 1, 'ACCEPTED',
        'Возможность получить более длинный неповторяющийся набор слов. вывод. Вырвал отдельные фразы и зла средневековый книгопечатник. Не имеет никакого отношения к обитателям водоемов при оценке качества. Небольшие проблемы: в xvi веке. Сыграет на основе оригинального трактата, благодаря чему появляется возможность получить более. Именно из его применили в качестве рыбы текст этот, несмотря на кириллический. Применили в xvi веке разной частотой, имеется разница в длине наиболее распространенных.',
        'Вырвал отдельные фразы и зла', 16, 3, 4),
       (current_time() - interval 9 day, 0, 'NEW',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        'Seventh post. Generated Lorem Ipsum placeholder text', 0, NULL, 4),
       (current_time() - interval 10 day, 1, 'ACCEPTED',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        'Eighth post', 8, 3, 2),
       (current_time() - interval 11 day, 1, 'ACCEPTED',
        'neque gravida in fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium nibh ipsum consequat nisl',
        'Generated Lorem Ipsum placeholder text', 3, 3, 6);

INSERT INTO post_comments (text, time, parent_id, post_id, user_id)
VALUES ('Отличная статья!', current_time() - interval 3 day, null, 3, 2),
       ('Спасибо! Полезная и актуальная информация!', current_time() - interval 3 day, null, 5, 4),
       ('Ласковые термиты кусают буратино за ушком', current_time() - interval 1 day, null, 8, 5),
       ('Освещать темный переулок айфоном - плохая примета.', current_time(), null, 2, 4),
       ('Спасаясь от воды, не прыгай в огонь.', current_time(), null, 6, 6),
       ('То, что вы слышали нечто так часто, что оно вам надоело, не значит, что это - правда.', current_time(), 2, 2,
        6),
       ('Колесо обозрения крутилось так быстро, что посетитель испугался себе на голову.', current_time(), 1, 3, 7);

INSERT INTO tags (name)
VALUES ('Java'),
       ('Kotlin'),
       ('Python'),
       ('SQL'),
       ('Hibernate'),
       ('Spring'),
       ('PHP'),
       ('Vaadin'),
       ('Flutter'),
       ('Dart');

INSERT INTO post_votes (time, value, post_id, user_id)
VALUES (current_time(), 1, 1, 3),
       (current_time(), 1, 1, 2),
       (current_time(), -1, 10, 4),
       (current_time(), 1, 1, 5),
       (current_time(), 1, 10, 1),
       (current_time(), -1, 1, 6),
       (current_time(), -1, 10, 6),
       (current_time(), 1, 3, 1),
       (current_time(), 1, 3, 3),
       (current_time(), -1, 3, 2),
       (current_time(), 1, 5, 3),
       (current_time(), 1, 5, 2),
       (current_time(), 1, 1, 2),
       (current_time(), -1, 8, 3),
       (current_time(), 1, 5, 4),
       (current_time(), 1, 6, 3),
       (current_time(), 1, 6, 2);

INSERT INTO tag2post (tag_id, post_id)
VALUES (1, 2),
       (1, 3),
       (2, 3),
       (1, 4),
       (1, 5),
       (1, 6),
       (1, 7),
       (2, 7),
       (2, 6),
       (2, 5),
       (2, 8),
       (1, 8),
       (4, 8),
       (6, 8),
       (3, 5),
       (2, 2),
       (3, 3),
       (10, 11),
       (9, 10),
       (8, 9),
       (7, 6),
       (5, 2),
       (3, 7),
       (3, 3);



